environment:
  YOUTUBE_API_KEY: "your-api-key-here"

steps:
  - name: Download and upload video
    run: |
      python upload_video.py $VIDEO_LINK
    env:
      VIDEO_LINK: "https://www.youtube.com/watch?v=12345"
